Updating workflows for moved notebooks

diff --git a/.github/actions/staging-notebook/action.yml b/.github/actions/staging-notebook/action.yml
--- a/.github/actions/staging-notebook/action.yml
+++ b/.github/actions/staging-notebook/action.yml
@@ -37,15 +37,15 @@ runs:
           exit 1
         fi
 
-    - name: Execute ONLY the ValidMind for model development series with heap staging
+    - name: Execute ONLY the ValidMind for development series with heap staging
       shell: bash
       if: ${{ steps.find_dev_env.outcome == 'success' }}
       run: |
           cd site
           cp ../${{ inputs.dev_env }} ../.env
           source ../.env
-          quarto render --profile exe-staging notebooks/EXECUTED/model_development &> render_errors.log || {
-            echo "Execute for ValidMind for model development series failed";
+          quarto render --profile exe-staging notebooks/EXECUTED/development &> render_errors.log || {
+            echo "Execute for ValidMind for development series failed";
             cat render_errors.log;
             exit 1;
           }
@@ -59,15 +59,15 @@ runs:
           exit 1
         fi
 
-    - name: Execute ONLY the ValidMind for model validation series with heap staging
+    - name: Execute ONLY the ValidMind for validation series with heap staging
       shell: bash
       if: ${{ steps.find_valid_env.outcome == 'success' }}
       run: |
           cd site
           cp ../${{ inputs.valid_env }} ../.env
           source ../.env
-          quarto render --profile exe-staging notebooks/EXECUTED/model_validation &> render_errors.log || {
-            echo "Execute for ValidMind for model validation series failed";
+          quarto render --profile exe-staging notebooks/EXECUTED/validation &> render_errors.log || {
+            echo "Execute for ValidMind for validation series failed";
             cat render_errors.log;
             exit 1;
           }
