Swapping the execution to new notebooks

diff --git a/.github/actions/demo-notebook/action.yml b/.github/actions/demo-notebook/action.yml
--- a/.github/actions/demo-notebook/action.yml
+++ b/.github/actions/demo-notebook/action.yml
@@ -33,14 +33,14 @@ runs:
           exit 1
         fi
 
-    - name: Execute ONLY the Intro for Model Developers notebook with heap development
+    - name: Execute ONLY the ValidMind for model development series with heap development
       shell: bash
       if: ${{ steps.find_env.outcome == 'success' }}
       run: |
           cd site
           source ../${{ inputs.env_file }}
-          quarto render --profile exe-demo notebooks/tutorials/intro_for_model_developers_EXECUTED.ipynb &> render_errors.log || {
-          echo "Execute for intro_for_model_developers_EXECUTED.ipynb failed";
+          quarto render --profile exe-demo notebooks/EXECUTED/model_development &> render_errors.log || {
+          echo "Execute for ValidMind for model development series failed";
           cat render_errors.log;
           exit 1;
           }
