Add quarto render steps to staging and prod workflows

diff --git a/.github/workflows/deploy-docs-prod.yaml b/.github/workflows/deploy-docs-prod.yaml
--- a/.github/workflows/deploy-docs-prod.yaml
+++ b/.github/workflows/deploy-docs-prod.yaml
@@ -1,6 +1,6 @@
 # Deploy our docs site to S3 whenever we push a commit to the main branch
 
-name: Deploy to S3 production bucket
+name: Deploy docs site to production
 
 on:
   push:
@@ -12,7 +12,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout repository
+        uses: actions/checkout@v2
+  
+      - name: Get latest Quarto release URL
+        id: get-quarto-url
+        run: |
+          API_URL="https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest"
+          DOWNLOAD_URL=$(curl -s $API_URL | jq -r '.assets[] | select(.name | endswith("linux-amd64.deb")).browser_download_url')
+          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
+  
+      - name: Download and install Quarto
+        run: |
+          wget ${{ env.DOWNLOAD_URL }} -O quarto-latest-linux-amd64.deb
+          sudo dpkg -i quarto-latest-linux-amd64.deb
+  
+      - name: Render Site
+        run: |
+            cd ./site 
+            quarto render &> render_errors.log || { 
+            echo "Quarto render failed immediately";
+            cat render_errors.log;
+            exit 1;
+            }
+
+      - name: Deploy docs site
         uses: actions/checkout@v2
 
       # Prod bucket is in us-east-1
