directing stderr to file

diff --git a/.github/workflows/render-site.yaml b/.github/workflows/render-site.yaml
--- a/.github/workflows/render-site.yaml
+++ b/.github/workflows/render-site.yaml
@@ -32,13 +32,23 @@ jobs:
     - name: Render Site
       run: |
           cd ./site 
-          quarto render
+          quarto render 2> render_errors.log
 
-    - name: Upload Quarto output
-      uses: actions/upload-artifact@v2
-      with:
-        name: quarto-output
-        path: ./site/_site/quarto-output # not sure about this as output
+    - name: Check for render errors
+      run: |
+        if [ -s site/render_errors.log ]; then
+          echo "Errors detected during render"
+          cat site/render_errors.log
+          exit 1
+        else
+          echo "No errors detected during render"
+        fi
+
+    # - name: Upload Quarto output
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: quarto-output
+    #     path: ./site/_site/quarto-output # not sure about this as output
   
 # I don't think we need this next one:
 
