Commenting out the render for now

diff --git a/.github/workflows/validate-docs-site.yaml b/.github/workflows/validate-docs-site.yaml
--- a/.github/workflows/validate-docs-site.yaml
+++ b/.github/workflows/validate-docs-site.yaml
@@ -20,14 +20,14 @@ jobs:
     - name: Fetch Quarto
       uses: ./.github/actions/fetch-quarto
 
-    - name: Render demo docs site
-      run: |
-          cd site 
-          quarto render --profile development &> render_errors.log || { 
-          echo "Quarto render failed immediately";
-          cat render_errors.log;
-          exit 1;
-          }
+    # - name: Render demo docs site
+    #   run: |
+    #       cd site 
+    #       quarto render --profile development &> render_errors.log || { 
+    #       echo "Quarto render failed immediately";
+    #       cat render_errors.log;
+    #       exit 1;
+    #       }
     
     # See if site/notebooks/ has updates
     - name: Filter changed files
